environment: hml

namespace: hml

replicaCount: 2

image:
  repository: challenge-devops
  pullPolicy: Never
  tag: hml

service:
  type: LoadBalancer
  port: 80

containerPort: 8000

otel:
  endpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
  serviceName: "challenge-devops-api"
  environment: "hml"