replicaCount: 1

image:
  repository: challenge-devops
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 80

containerPort: 8000

otel:
  endpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
  serviceName: "challenge-devops-api"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"