apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      nodeSelector:
        role: platform-app

      containers:
        - name: {{ .Release.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false

          resources:
{{ toYaml .Values.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: challenge-devops-config
            - secretRef:
                name: challenge-devops-secret

          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}

            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName | quote }}

            - name: DEPLOYMENT_ENVIRONMENT
              value: {{ .Values.environment | quote }}

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            failureThreshold: 30
            periodSeconds: 5