apiVersion: apps/v1

kind: Deployment

metadata:
  name: challenge-devops
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: challenge-devops

  template:

    metadata:
      labels:
        app: challenge-devops

    spec:
      containers:

        - name: challenge-devops

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}