apiVersion: v1

kind: Service

metadata:
  name: challenge-devops-service
  namespace: {{ .Values.namespace }}

spec:

  selector:
    app: challenge-devops

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

  type: {{ .Values.service.type }}