nodeSelector:
  role: platform-observability

resources:
  requests:
    cpu: 100m
    memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi

service:
  type: ClusterIP

adminUser: admin
adminPassword: admin123