server:
  nodeSelector:
    role: platform-observability

  resources:
    requests:
      cpu: 500m
      memory: 512Mi

    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false